services:
  app:
    container_name: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_BASE_URL: ${SPRING_APPLICATION_BASE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_SENDGRID_API_KEY: ${SPRING_SENDGRID_API_KEY}
      SPRING_SENDGRID_FROM_EMAIL: ${SPRING_SENDGRID_FROM_EMAIL}
      SPRING_SENDGRID_FROM_NAME: ${SPRING_SENDGRID_FROM_NAME}
      SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL: ${SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL}
      SPRING_AWS_S3_BUCKET_NAME: ${SPRING_AWS_S3_BUCKET_NAME}
      SPRING_AWS_S3_REGION: ${SPRING_AWS_S3_REGION}
      SPRING_AWS_S3_ACCESS_KEY_ID: ${SPRING_AWS_S3_ACCESS_KEY_ID}
      SPRING_AWS_S3_SECRET_ACCESS_KEY: ${SPRING_AWS_S3_SECRET_ACCESS_KEY}
      STRIPE_API_PUBLISHABLE_KEY: ${STRIPE_API_PUBLISHABLE_KEY}
      STRIPE_API_SECRET_KEY: ${STRIPE_API_SECRET_KEY}
      STRIPE_API_WEBHOOK_SECRET: ${STRIPE_API_WEBHOOK_SECRET}
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonar_db
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db/${SONARQUBE_DB_NAME}
      SONAR_JDBC_USERNAME: ${SONARQUBE_DB_USER}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_DB_PASSWORD}
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres
    container_name: sonar_db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${SONARQUBE_DB_USER}
      POSTGRES_PASSWORD: ${SONARQUBE_DB_PASSWORD}
      POSTGRES_DB: ${SONARQUBE_DB_NAME}
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data
  sonar_db_data:
    name: sonar_db_data
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db: