services:
  app:
    container_name: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_BASE_URL: ${SPRING_APPLICATION_BASE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_SENDGRID_API_KEY: ${SPRING_SENDGRID_API_KEY}
      SPRING_SENDGRID_FROM_EMAIL: ${SPRING_SENDGRID_FROM_EMAIL}
      SPRING_SENDGRID_FROM_NAME: ${SPRING_SENDGRID_FROM_NAME}
      SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL: ${SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL}
      SPRING_AWS_S3_BUCKET_NAME: ${SPRING_AWS_S3_BUCKET_NAME}
      SPRING_AWS_S3_REGION: ${SPRING_AWS_S3_REGION}
      SPRING_AWS_S3_ACCESS_KEY_ID: ${SPRING_AWS_S3_ACCESS_KEY_ID}
      SPRING_AWS_S3_SECRET_ACCESS_KEY: ${SPRING_AWS_S3_SECRET_ACCESS_KEY}
      STRIPE_API_PUBLISHABLE_KEY: ${STRIPE_API_PUBLISHABLE_KEY}
      STRIPE_API_SECRET_KEY: ${STRIPE_API_SECRET_KEY}
      STRIPE_API_WEBHOOK_SECRET: ${STRIPE_API_WEBHOOK_SECRET}
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tempdb
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    name: postgres_data
  mysql_data:
    name: mysql_data
  redis_data:
    name: redis_data