services:
  db:
    container_name: postgresql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: tempdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
    name: postgres_data
  mysql_data:
    name: mysql_data