FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Official OpenJDK runtime image to run the app
FROM eclipse-temurin:17-jdk-alpine
ARG SPRING_APPLICATION_BASE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATA_REDIS_HOST
ARG SPRING_DATA_REDIS_PORT
ARG JWT_SECRET_KEY
ARG SPRING_SENDGRID_API_KEY
ARG SPRING_SENDGRID_FROM_EMAIL
ARG SPRING_SENDGRID_FROM_NAME
ARG SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL
ARG SPRING_AWS_S3_BUCKET_NAME
ARG SPRING_AWS_S3_REGION
ARG SPRING_AWS_S3_ACCESS_KEY_ID
ARG SPRING_AWS_S3_SECRET_ACCESS_KEY
ARG STRIPE_API_PUBLISHABLE_KEY
ARG STRIPE_API_SECRET_KEY
ARG STRIPE_API_WEBHOOK_SECRET

WORKDIR /app
COPY --from=build /build/target/demo-*.jar /app/

EXPOSE 8080

ENV SPRING_APPLICATION_BASE_URL=${SPRING_APPLICATION_BASE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
ENV SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV SPRING_SENDGRID_API_KEY=${SPRING_SENDGRID_API_KEY}
ENV SPRING_SENDGRID_FROM_EMAIL=${SPRING_SENDGRID_FROM_EMAIL}
ENV SPRING_SENDGRID_FROM_NAME=${SPRING_SENDGRID_FROM_NAME}
ENV SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL=${SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL}
ENV SPRING_AWS_S3_BUCKET_NAME=${SPRING_AWS_S3_BUCKET_NAME}
ENV SPRING_AWS_S3_REGION=${SPRING_AWS_S3_REGION}
ENV SPRING_AWS_S3_ACCESS_KEY_ID=${SPRING_AWS_S3_ACCESS_KEY_ID}
ENV SPRING_AWS_S3_SECRET_ACCESS_KEY=${SPRING_AWS_S3_SECRET_ACCESS_KEY}
ENV STRIPE_API_PUBLISHABLE_KEY=${STRIPE_API_PUBLISHABLE_KEY}
ENV STRIPE_API_SECRET_KEY=${STRIPE_API_SECRET_KEY}
ENV STRIPE_API_WEBHOOK_SECRET=${STRIPE_API_WEBHOOK_SECRET}

CMD java -jar -Dspring.application.base-url=${SPRING_APPLICATION_BASE_URL} \
            -Dspring.datasource.username=${SPRING_DATASOURCE_USERNAME} \
            -Dspring.datasource.password=${SPRING_DATASOURCE_PASSWORD} \
            -Dspring.datasource.url=${SPRING_DATASOURCE_URL} \
            -Dspring.redis.host=${SPRING_DATA_REDIS_HOST} \
            -Dspring.redis.port=${SPRING_DATA_REDIS_PORT} \
            -Dsecurity.jwt.secret-key=${JWT_SECRET_KEY} \
            -Dapp.sendgrid.api-key=${SPRING_SENDGRID_API_KEY} \
            -Dapp.sendgrid.from-email=${SPRING_SENDGRID_FROM_EMAIL} \
            -Dapp.sendgrid.from-name=${SPRING_SENDGRID_FROM_NAME} \
            -Dapp.sendgrid.template.reset-password-email=${SPRING_SENDGRID_TEMPLATE_RESET_PASSWORD_EMAIL} \
            -Daws.s3.bucket-name=${SPRING_AWS_S3_BUCKET_NAME} \
            -Daws.s3.region=${SPRING_AWS_S3_REGION} \
            -Daws.s3.access-key-id=${SPRING_AWS_S3_ACCESS_KEY_ID} \
            -Daws.s3.secret-access-key=${SPRING_AWS_S3_SECRET_ACCESS_KEY} \
            -Dstripe.api.publishable-key=${STRIPE_API_PUBLISHABLE_KEY} \
            -Dstripe.api.secret-key=${STRIPE_API_SECRET_KEY} \
            -Dstripe.api.webhook-secret=${STRIPE_API_WEBHOOK_SECRET} \
            demo-0.0.1-SNAPSHOT.jar